# Solutions of the Machine Learning Interviews book by Chip Huyen

In [1]:
# imports used throughout the notebook
import numpy as np

## 5.1 Algebra and (little) calculus

### 5.1.1 Vectors

#### 1 Dot product

i. The dot product of two vectors determines how the vectors are aligned w.r.t each other. Higher the dot product, more the two vectors will be aligned

ii The dot product is maximum implies $u.v = ||u|| ||v||cos\theta = ||u||$. Therefore, $v$ will just be a unit vector in the direction of $u$ i.e $v = \frac{u}{||u||}$

#### 2. Outer product

i $a = np.array([3, 2, 1]), b = np.array([-1, 0, 1])$

In [16]:
## 3. Two vectors a & b are linearly independent if a =/= cb where c is a constant 

In [17]:
## 4. 

In [18]:
## 5. The span dimennsion is d since each vector can be represented by a basis vector of dimension d

#### 6 
i. Norm determines the length or magnitude of vectors in a space.
- $L_0 = \sum_{i=1}^{n}|x_i|^0 = \{\#i:x_i \ne 0\}$ s.t $0^0 = 0$ It is the number of non-zero elements in the vector. 
- $L_1 = \sum_{i=1}^{n}|x_i|$
- $L_2 = \sqrt{\sum_{i=1}^{n}|x_i|^2}$
- $L_{norm} = L_p = (\sum_{i=1}^{n}|x_i|^p)^\frac{1}{p}$

### 5.1.2 Matrices 

In [20]:
## 1. Because there exists vectors x s.t Mx = lx where l is a constant known as the eigenvalue. 
# In this case, the matrix multiplication is just a linear transformation of the vector x by the value l

In [21]:
## 2. The inverse of a matrix M reverses the transformation done by the matrix M. 
# In other words, applying the matrix inverse following the matrix transformation is 
# equivalent to applying no transformation at all. This is mathematically justified by MM^-1 = I
# where I is the identity matrix

In [22]:
## 3. 

In [23]:
## 4. 

In [24]:
## 5. tr(A) = 3+3+2-1 = 7, det(A) = 3*3*2*-1 = -18

In [25]:
## 6. 

In [26]:
## 7. 

In [27]:
## 8. 
# i
# x = A^(-1)b

# ii
# when A^(-1) exists

# iii
# 

# iv
# 

In [28]:
# 9. Derivative
# i
# The derivative represents the change in the output corresponding to the change in the input

# ii
# Derivative works for scalars, gradient works for 1d vectors and Jacobian works for matrices

In [29]:
## 10. J in R^(mxd)

In [30]:
## 11. 

## 6.1 Algorithms

In [32]:
## 10. Calculating a mathematical expression
inp = "10 * 4 + (4 + 3) / (2 - 1)"

stack = []
def check(inp):
    num = ""
    for c in inp:
        try:
            int(c)
            num += c
        except:
            print("Error parsing")
            pass
        finally:
            stack.append(num)
            num = ""
            
check(inp)
stack

Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing
Error parsing


['1',
 '0',
 '',
 '',
 '',
 '4',
 '',
 '',
 '',
 '',
 '4',
 '',
 '',
 '',
 '3',
 '',
 '',
 '',
 '',
 '',
 '2',
 '',
 '',
 '',
 '1',
 '']

## 7.2 Sampling and creating training data

In [33]:
## 1. 6C2 + 4C1 = 15 + 4 = 19 ways

In [34]:
## 2. Sampling with replacement leads to unique samples, without replacement may have duplicate samples
# We should use w/ replacement when we want to randomly sample indices or locations of the data

In [35]:
## 3. 

In [36]:
## 4. 

In [37]:
## 5. 

## 7.3 Objective functions, metrics, and evaluation

#### 6 
The problem in this case is that the data will have a huge class imbalance. I would know that the relative proportion of people having cancer will be very less. Let's consider that there were 1000 patients in total. And out of these, only 1 patient had cancer. Then the accuracy in this case will come out to be 99.9% if the model correctly predicted the patients who did not have cancer. In other words, $TP = 0, FP = 0, TN = 999, FN = 1$ and: 

$$Acc = \frac{TP + TN}{TP + FP + TN + FN} = \frac{0+999}{0+0+999+1} = 99.9\%$$

But the precison and recall in this case will be 0 since the model did not predict the patient with cancer. Hence, the F1-score, in this case, will also be zero. We care about the precision and recall because the patients having cancer but predicted incorrectly is more dangerous than predicting if the patient has cancer but is actually healthy. To summarize, whenever there is a class imbalance or the False Positives and False Negatives are more important, the accuracy is a bad metric and F1-score should be used.

#### 7
i. F1 score is a better metric when there are imbalanced classes in the dataset (as seen in the previous question). Also, when it more important to look at the False Positives and False Negatives, F1-score should be preferred instead of accuracy.

ii. Yes, we can use F1-score for multi-class classification problems. There are three variants-macro-averaging, micro-averaging and weighted-averaging. 
- In macro-averaging, the per-class precision, recall and F1-scores are computed. Then the macro-averaged F1-score is the mean of the per-class scores.
- In micro-averaging, first the micro-averaged precison and recall are computed. In this case, all the samples are considered together. This leads to equal values of the precision and recall and since $F1 = \frac{2*P*R}{P + R}$, F1-score is equal to the precision and recall.
- In weighted-averaging,  the per-class F1-scores are weighted by the class support and then averaged. 

#### 8
i. $$P = \frac{30}{30+5} = 0.86$$ 
$$R = \frac{30}{30+20} = 0.50$$
$$F1 = \frac{2*0.86*0.50}{0.86+0.50} = 0.63$$

ii. 

#### 16
i. MPE or MLE (Maximum Likelihood Estimation) finds the parameters that optimize the likelihood of the data whereas MAP finds the optimal parameters after seeing the data. In MLE, we care about the data distribution $p(D|\theta)$ while in MAP, we care about the posterior distribution $p(\theta|D)$.

ii. Let's consider the example of coin flips. Given a sequence of coin flips, we have to predict the next flip. Let $\theta$ denote the probability of getting a tail in the next flip i.e $p(F=\mathcal{T}) = \theta$. For MLE, we have the point estimate $\theta_{MPE} = \frac{\mathcal{T}}{\mathcal{T} + \mathcal{H}}$. And for MAP, if we choose Beta as the prior distribution with $a=2, b=1$, we have the point estimate $\theta_{MAP} = \frac{\mathcal{T}+a-1}{\mathcal{T}+\mathcal{H}+a+b-2}$. Beta is the distribution which approximates other distributions based on the parameters $a$ and $b$. Beta is also the conjugate prior of Bernoulli distribution which allows for a closed form solution of the MAP. 

Now, if we have the following sequence of coin flips:
$$\mathcal{H} \space\space \mathcal{H}$$
- $\theta_{MPE} = 0$ since there were no tails in the previous flips 
- $\theta_{MAP} = 0.33$

Hence, MPE and MAP would produce different results when the prior distribution is not uniform. 

## 8.1.2 Classical Machine Learning

#### 1


#### 2
Feature scaling is important where the data is not linearly separable. Since Logistic Regression is a linear classifier, it will not be able to separate the classes in the dataset if feature scaling is not performed.

#### 3
Fraud detection is a binary classification problem. The algorithms to use for this are Logistic Regression, SVM, Random Forest, MLP.

#### 6
i. k is a hyperparameter. Its value should be chosen based on the cross-validation trials which lead to the maximum accuracy.

ii. When the value is increased, the accuracy increases but after a certain value, the accuracy will decrease.

iii. When k is small, there is more bias and less variance. As k increases, bias decreases and variance increases. For large k, bias is small and variance is high.

#### 9
i. $$A_{directed} = 
\begin{bmatrix}
0 & 1 & 0 & 1 & 1 \\
0 & 0 & 1 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0
\end{bmatrix}$$

ii. $$A_{undirected} = 
\begin{bmatrix}
0 & 1 & 0 & 1 & 1 \\
1 & 0 & 1 & 1 & 0 \\
0 & 1 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 & 0
\end{bmatrix}$$

iii. The adjacency matrices of two isomorphic graphs will be equal upto some ordering of the vertices

## 8.2.4 Other

#### 1
Autoencoders are useful for dimensionality reduction or learning a latent representation of data. They are particularly useful in the case of unsupervised learning where there is no labeled data.

# 8.3 Training neural networks

#### 3

In [96]:
x = np.array([3, 4])
y = 2
w1 = np.random.randn(len(x)+1)
w2 = np.random.randn(len(x))

def relu(x):
    return x if x>0 else 0

w1, w2

(array([ 0.33706809,  0.70988615, -0.59967289]),
 array([ 0.20920099, -0.28525913]))

In [97]:
# forward pass
def forward(x, w1, w2):
    h = w1.dot(np.concatenate(([1], x)))
    h_relu = relu(h)
    # print(h_relu)
    y_hat = w2.dot(np.concatenate(([1.0], [h_relu])))
    cache = tuple([x, h_relu])
    
    return y_hat, cache

def backward(loss, y_hat, cache):
    x, h_relu = cache
    dloss = -2*(y-y_hat)
    dy_hat = w2[1]
    dh_relu = 1 if h_relu > 0 else 0
    dh = np.concatenate(([1], x))
    dw1 = dloss*dy_hat*dh_relu*dh
    dw2 = dloss*h_relu
    
    return dw1, dw2

In [100]:
lr = 0.001
for i in range(5):
    y_hat, cache = forward(x, w1, w2)
    loss = (y-y_hat)**2
    dw1, dw2 = backward(loss, y_hat, cache)
    update_w1 = -lr*dw1
    update_w2 = -lr*dw2
    w1 += update_w1
    w2 += update_w2
    
    print(loss)

3.1981451676147725
3.1981451676147725
3.1981451676147725
3.1981451676147725
3.1981451676147725


In [101]:
w1, w2

(array([ 0.32674053,  0.67890347, -0.64098313]),
 array([ 0.21166413, -0.28279598]))

In [102]:
forward(x, w1, w2)[0], y

(0.21166413456119135, 2)